spring.application.name=medilabopatient
server.port=8081

################### DataSource Configuration ##########################
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

################### Hibernate Configuration ##########################
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect